### ISSUE TITLE
Add Ender Storage?

### ISSUE THREAD

**Issue by Voxel-Friend** [copygirl/obsidian-Modpack#15]
Reason: With little to no automation mods added, these aren't as overpowered as they normally would be. Plus, the recipe should be relatively easy to tweak I'd say.

**Comment by copygirl** [comment]
Even less of a reason to use minecarts with chests, so I'd rather not.

**Comment by Voxel-Friend** [comment]
Fair enough. The thing is that I do not yet have a full grasp of the vision you have for the pack. Perhaps If you could think of a few guidelines for how you want the pack to feel, it could help me make better suggestions for improvement.

**Comment by copygirl** [comment]
Closing the issue for now since I don't think the mod fits. Input still welcome.
