### ISSUE TITLE
Add Special AI?

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [copygirl/obsidian-Modpack#23]
Hello,

would you consider adding SpecialAI mod from FatherToast?

http://www.curse.com/mc-mods/minecraft/224301-special-ai

It can be set to make passive mobs neutral, meaning they'll agro if you(or mobs) beat them up.

\o/

**Comment by copygirl** [comment]
Good idea, I'll definitely consider it!

> Special AI adds a variety of new AI patterns to mobs, including: monsters idly breaking your light sources and certain blocks, an attack AI for "passive" mobs, mounting AI, and a pile of unique combat AIs to keep you on your toes!

Breaking torches might be a little annoying. Perhaps only enable it for just a few rare Special Mobs?
