### ISSUE TITLE
Add Dr. Cyano's Lootable Bodies?

### ISSUE THREAD

**Issue by copygirl** [copygirl/obsidian-Modpack#3]
http://minecraftforum.net/forums/x/2298198

> This mod protects your items from despawning when you die by storing them on a dead body that you can later loot to get your stuff back. Your dead body is unharmed by fire, explosions, and falling, with configurations options to make your lootable bodies completely invulnerable (or more vulnerable, if you so choose). Simply right-click on a dead body to access its inventory. Use a shovel to dispose of your body after you looted it (3 hits with a shovel will remove the body).

As the gravestones mod really doesn't fit into the pack in my opinion, this could be an interesting alternative that fits well and may not always be able to safe all items. Question is whether it works well together with backpacks, Baubles and Smart Moving.

**Comment by die9091** [comment]
Yes add dis mod

**Comment by copygirl** [comment]
After testing the mod, I have to say I don't really like it. First of all, I think it fits under the "don't add mods that just do one small thing" rule. Here's the other reasons:
- Corpses can be pushed and punched around, even if the `hurt_by_weapons` option is off.
- No fast looting option, apparently (may be possible by destroying the corpse).
- No option to instantly destroy or speed up decay of empty corpses.
- GUI could be improved:
  - Special armor and held item slots instead of them just being the first 5 slots.  
    Perhaps even Baubles support so they would have their own special slots.
  - Display death message (maybe on a small tomb stone).

Will close the issue for now. There's the possibility of adding the mod in the future if these points get addressed, though I feel like it's not important enough to go bug the mod author about it, especially considering the 1.7 version is a backport.
