### ISSUE TITLE
About Helping with Pack Developement

### ISSUE THREAD

**Issue by Voxel-Friend** [copygirl/obsidian-Modpack#38]
A bit of backstory...
It has been my dream ever since I discovered modded Minecraft to be apart of something special. To have something to look at and be proud of what I've contributed. I want to add more to the community at large, I want to feel welcome. However, due to the limitations of my social skills, it has been a monumental task to find a way to contribute. When I discovered the existence of this sever, I immediately was welcomed by someone who I could relate to. I feel I have finally found my opportunity to do something meaningful.

But...

 I know that you will need me to prove myself able to help with this pack. This brings me to the reason I have opened this issue. Instead of throwing suggestions your way and hoping you'll implement them, I have an idea. It would involve a lot of work on my part, but I am willing to prove my dedication to this pack.

Railcraft and Immersive Engineering are both mods you have expressed interest in before. However, It seemed that you were hesitant, due to already having a lot on your plate already. If we could come up with some Ideas on things to tweak to fit the pack, I would be willing to try my hand on scripting (Minetweaker/Modtweaker) and editing (configs) to better balance to the pack.

I apologize for the wall of text, and if I'm being too formal about this. I would love to discuss this more at length.

**Comment by copygirl** [comment]
First off, you should totally join the #obsidian IRC channel (on Esper.net).

Like I said I wouldn't mind throwing Immersive Engineering on to test it out (but haven't played with it yet), though I still feel the same about Railcraft: Consider it once people actually use Vanilla rails and minecarts.

And I'd love someone helping with the pack, thank you! :heart:
