### ISSUE TITLE
Add Immersive Engineering?

### ISSUE THREAD

**Issue by copygirl** [copygirl/obsidian-Modpack#8]
http://minecraft.curseforge.com/mc-mods/231951-immersive-engineering

> Immersive Engineering is a tech mod with a certain charm.
> Based on the ideas and concepts, and with all assets created by Damien Hazard, it aims to bring a realism-inspired, retro-futuristic experience of technology and engineering to the user. [...]
> 
> The mod features Power Generation in forms of waterwheels, windmills, biodiesel and more and many of its machines are multiblocks!

Have not had the chance to check it out yet. It _could_ be a good fit.

**Comment by Voxel-Friend** [comment]
It Definitely have my vote! High end Machines require Massive power, so as long as no other mod adds power gen, should be sweet. food for thought though, has no native piping system yet, though the mod adds liquid fuel...

**Comment by BarbasTheDog** [comment]
Although I love the mod, I think the only things that would really fit the pack's aesthetic would be the waterwheel and the windmills (as well as the power components, of course).

The big machines like Diesel Generators, the Bucket wheel miner and so on just seem just a bit too industrial compared to flaxbeard's and the rest of the pack.

That being said, just the windmills and waterwheel already make it more than worth it. xD

**Comment by copygirl** [comment]
Finally took the time to look at a spotlight. It's a really cool mod, and would make for an interesting mod to base things around, but we already have Flaxbeard's Steam Power. I'd rather not include it.

**Comment by copygirl** [comment]
I will close this issue for now since I don't see a way to include the mod even with heavy config and recipe changes. If someone wants to share their thoughts still, you're free to do so.
